name: Slack Channel Report

on:
  schedule:
    - cron: "0 3 1 * *"
  workflow_dispatch:
    inputs:
      dateFrom:
        description: 'The start date for the channel report in MM/DD/YYYY format (default: beginning of the LAST month)'
        required: false
      dateTo:
        description: 'The end date for the channel report in MM/DD/YYYY format (default: today)'
        required: false
      channelName:
        description: 'Channel name'
        required: false

jobs:
  channel-report:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      GOOGLE_CERT: ${{ secrets.GOOGLE_CERT }}
      DATE_FROM: ${{ inputs.dateFrom }}
      DATE_TO: ${{ github.event.inputs.dateTo }}
      CHANNEL_NAME: ${{ github.event.inputs.channelName }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Print input data
        run: echo "The input is dateFrom= ${{ inputs.dateFrom }} ; dateTo=${{ inputs.dateTo }}"

      - name: Generate channel report
        run:
          node dist/src/fetchAndAnalyze.js
